import { useState } from 'react';
import { resolve } from '../utils/assetUrl';
import { useTheme } from '../contexts/themeStore';
import ContributionGraph from './ContributionGraph';

type Props = { username: string };

/**
 * The 3D contribution art generated by the github-profile-3d-contrib action
 * (see .github/workflows/profile-3d.yml).
 *
 * The gitblock variant draws its own light baseplate, so it is used in light
 * mode; the night variant suits dark. The files only exist once the workflow
 * has run, so a missing image falls back to the flat calendar rather than
 * showing a broken graphic.
 */
const Contributions3D = ({ username }: Props) => {
  const { theme } = useTheme();
  const [failed, setFailed] = useState(false);

  if (failed) return <ContributionGraph username={username} since={2022} />;

  const file = theme === 'light' ? 'profile-gitblock.svg' : 'profile-night-green.svg';

  return (
    <figure className={`contrib3d contrib3d-${theme}`}>
      <img
        // Keyed so switching theme swaps the source instead of reusing the
        // previous image element (and its error state).
        key={file}
        className="contrib3d-img"
        src={resolve(`profile-3d/${file}`)}
        alt={`3D chart of ${username}'s GitHub contributions over the past year`}
        width={1280}
        height={850}
        loading="lazy"
        onError={() => setFailed(true)}
      />
    </figure>
  );
};

export default Contributions3D;
